{
  programs.nixvim.plugins.transparent = {
    enable = true;
    settings = {
      groups = [
        "Normal"
        "NormalNC"
        # "EndOfBuffer"
        # "SignColumn"
        # "LineNr"
        # "CursorLine"
        # "CursorLineNr"
        # "StatusLine"
        # "StatusLineNC"
      ];
      extra_groups = [
        # "NormalFloat"
        # "FloatBorder"
        # "TelescopeBorder"
        # "TelescopePromptBorder"
        # "TelescopeResultsBorder"
        # "TelescopePreviewBorder"
        # "TelescopeNormal"
        # "TelescopePromptNormal"
        # "TelescopeResultsNormal"
        # "TelescopePreviewNormal"
        # "Pmenu"
        # "PmenuSel"
        # "PmenuSbar"
        # "PmenuThumb"
        # "CmpItemMenu"
        # "CmpItemAbbr"
        # "CmpItemKind"
        # "ScrollbarHandle"
        # "ScrollbarThumb"
        # "Scrollbar"
        # "ScrollbarBorder"
        # "WhichKeyFloat"
        # "WhichKeyBorder"
        # "WhichKeyDesc"
        # "WhichKeyGroup"
        # "NotifyERRORBorder"
        # "NotifyWARNBorder"
        # "NotifyINFOBorder"
        # "NotifyDEBUGBorder"
        # "NotifyTRACEBorder"
        # "NotifyBackground"
        # # DAP UI
        # "DapUIVariable"
        # "DapUIScope"
        # "DapUIType"
        # "DapUIValue"
        # "DapUIModifiedValue"
        # "DapUIDecoration"
        # "DapUIThread"
        # "DapUIStoppedThread"
        # "DapUISource"
        # "DapUILineNumber"
        # "DapUIFloatBorder"
        # "DapUIWatchesHeader"
        # "DapUIWatchesEmpty"
        # "DapUIWatchesValue"
        # "DapUIWatchesError"
        # "DapUIBreakpointsPath"
        # "DapUIBreakpointsInfo"
        # "DapUIBreakpointsCurrentLine"
        # "DapUIBreakpointsLine"
        # # DAP virtual text
        # "NvimDapVirtualText"
        # "NvimDapVirtualTextError"
        # "NvimDapVirtualTextChanged"
      ];
      extra_groups_transparent = [
        # "NvimTreeNormal"
        # "NvimTreeCertSplit"
        # "NvimTreeNormalNC"
      ];
    };
  };
}
