gui:
  showIcons: true
git:
  paging:
    colorArg: always
    paper: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(blue)%h%C(reset) %C(green)%ad%C(reset) %C(magenta)%an%C(reset)%n%C(white)%s%C(reset)'
  branchLogCmd: >
    git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' 
    --pretty=format:'%C(blue)%h%C(reset) %C(green)%ad%C(reset) %C(magenta)%an%C(reset)%n%C(white)%s%C(reset)' {{branchName}}
disableMerging: false
disableRebasing: false

theme:
  activeBorderColor:
    - '#89b4fa'
    - bold
  inactiveBorderColor:
    - '#a6adc8'
  optionsTextColor:
    - '#89b4fa'
  selectedLineBgColor:
    - '#313244'
  cherryPickedCommitBgColor:
    - '#45475a'
  cherryPickedCommitFgColor:
    - '#89b4fa'
  unstagedChangesColor:
    - '#f38ba8'
  defaultFgColor:
    - '#cdd6f4'
  searchingActiveBorderColor:
    - '#f9e2af'

authorColors:
  '*': '#b4befe'
